# Generated by Django 4.1.4 on 2023-02-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование категории')),
                ('photo', models.ImageField(upload_to='photo/categoriesProducts/%Y/%m/%d/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Категория цветов',
                'verbose_name_plural': 'Категории цветов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Наименование продукта')),
                ('photo', models.ImageField(upload_to='photo/Products/%Y/%m/%d/', verbose_name='Фотография')),
                ('description', models.TextField(max_length=300, verbose_name='Краткое описание(300 символов)')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('is_active', models.BooleanField(verbose_name='Опубликованно')),
                ('popular', models.BooleanField(verbose_name='Отображается на главной странице(может быть 3)')),
                ('product_is_day', models.BooleanField(verbose_name='Продукт недели(может быть один)')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoriesproduct', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
            },
        ),
    ]
